# Generated by Django 5.1.3 on 2024-11-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_questao', models.CharField(choices=[('ME', 'Múltipla Escolha'), ('CE', 'Certo ou Errado')], max_length=2, verbose_name='Tipo de Questão')),
                ('enunciado', models.TextField()),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentários')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.materia', verbose_name='Matéria')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='QuestaoCertoErrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_correta', models.BooleanField(verbose_name='Resposta Correta')),
                ('questao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao')),
            ],
            options={
                'verbose_name': 'Questão de Certo ou Errado',
                'verbose_name_plural': 'Questões de Certo ou Errado',
            },
        ),
        migrations.CreateModel(
            name='QuestaoMultiplaEscolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_a', models.CharField(max_length=200)),
                ('alternativa_b', models.CharField(max_length=200)),
                ('alternativa_c', models.CharField(max_length=200)),
                ('alternativa_d', models.CharField(max_length=200)),
                ('alternativa_e', models.CharField(max_length=200)),
                ('resposta_correta', models.CharField(max_length=1, verbose_name='Resposta Correta')),
                ('questao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao')),
            ],
            options={
                'verbose_name': 'Questão de Múltipla Escolha',
                'verbose_name_plural': 'Questões de Múltipla Escolha',
            },
        ),
    ]
