# Generated by Django 5.1.3 on 2024-11-30 11:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Banca',
                'verbose_name_plural': 'Bancas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Matéria',
                'verbose_name_plural': 'Matérias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2024)])),
                ('tipo_questao', models.CharField(choices=[('ME', 'Múltipla Escolha'), ('CE', 'Certo/Errado')], max_length=2)),
                ('dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('banca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questoes.banca')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.materia')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='questoes.questao')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoCertoErrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gabarito', models.BooleanField(default=False)),
                ('questao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao')),
            ],
        ),
        migrations.CreateModel(
            name='QuestaoMultiplaEscolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa_a', models.TextField(max_length=200)),
                ('alternativa_b', models.TextField(max_length=200)),
                ('alternativa_c', models.TextField(max_length=200)),
                ('alternativa_d', models.TextField(max_length=200)),
                ('alternativa_e', models.TextField(blank=True, max_length=200)),
                ('gabarito', models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D'), ('E', 'Alternativa E')], default='A', max_length=1)),
                ('questao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='questoes.materia')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['materia__nome', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='questao',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questoes.subcategoria'),
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=1)),
                ('esta_correta', models.BooleanField(default=False)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questoes.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_resposta'],
                'unique_together': {('usuario', 'questao')},
            },
        ),
    ]
