# Generated by Django 5.1.3 on 2024-12-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='dificuldade',
            field=models.CharField(choices=[('F', 'Fácil'), ('M', 'Médio'), ('D', 'Difícil')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='questao',
            name='tipo_questao',
            field=models.CharField(choices=[('ME', 'Múltipla Escolha'), ('CE', 'Certo/Errado')], default='ME', max_length=2),
        ),
    ]
