# Generated by Django 5.1.3 on 2024-11-29 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0006_alter_questao_options_remove_questao_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostausuario',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='respostausuario',
            name='data_resposta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
