# Generated by Django 5.1.3 on 2024-11-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questoes', '0007_alter_respostausuario_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questaocertoerrado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questaomultiplaescolha',
            options={},
        ),
        migrations.AlterModelOptions(
            name='respostausuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='questaocertoerrado',
            name='resposta_correta',
        ),
        migrations.RemoveField(
            model_name='questaomultiplaescolha',
            name='resposta_correta',
        ),
        migrations.RemoveField(
            model_name='respostausuario',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='questaocertoerrado',
            name='gabarito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questaomultiplaescolha',
            name='gabarito',
            field=models.CharField(choices=[('A', 'Alternativa A'), ('B', 'Alternativa B'), ('C', 'Alternativa C'), ('D', 'Alternativa D'), ('E', 'Alternativa E')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='questao',
            name='tipo_questao',
            field=models.CharField(choices=[('ME', 'Múltipla Escolha'), ('CE', 'Certo ou Errado')], default='ME', max_length=2, verbose_name='Tipo de Questão'),
        ),
        migrations.AlterField(
            model_name='questaomultiplaescolha',
            name='alternativa_a',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questaomultiplaescolha',
            name='alternativa_b',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questaomultiplaescolha',
            name='alternativa_c',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questaomultiplaescolha',
            name='alternativa_d',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questaomultiplaescolha',
            name='alternativa_e',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='respostausuario',
            name='data_resposta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='respostausuario',
            name='esta_correta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='respostausuario',
            name='resposta',
            field=models.CharField(max_length=1),
        ),
    ]
